spring:
  cloud:
    stream:
      default-binder: kafka
      bindings:
        output:
          destination: test-topic
          content-type: text/plain            
        input:
          destination: test-topic
          content-type: text/plain
          consumer:
            headerMode: raw
            concurrency: 3